MoviesRecommendationSystem/Controllers/EditorsController.cs
namespace MoviesRecommendationSystem.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MoviesRecommendationSystem.Infrastructure;
    using MoviesRecommendationSystem.Models.Editors;
    using MoviesRecommendationSystem.Services.Editors;

    using static WebConstants;
    using static Common.ControllerConstants.Editors;

    public class EditorsController : Controller
    {
        private readonly IEditorService editorService;

        public EditorsController(IEditorService editorService)
            => this.editorService = editorService;

        [Authorize]
        public IActionResult Become()
            => View();

        [HttpPost]
        [Authorize]
        public IActionResult Become(BecomeEditorFormModel editor)
        {
            var userId = User.GetId();

            var userIsAlreadyEditor = this.editorService.UserIsEditor(userId);

            if (userIsAlreadyEditor)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(editor);
            }

            this.editorService.Create(
                editor.FirstName,
                editor.LastName,
                editor.BirthDate,
                userId);

            TempData[GlobalMessageKey] = SubmissionSentMessage;

            return RedirectToAction(nameof(HomeController.Index), HomeControllerName);
        }
    }
}

MoviesRecommendationSystem/Controllers/MoviesController.cs
namespace MoviesRecommendationSystem.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using AutoMapper;

    using MoviesRecommendationSystem.Infrastructure;
    using MoviesRecommendationSystem.Models.Movies;
    using MoviesRecommendationSystem.Services.Editors;
    using MoviesRecommendationSystem.Services.Movies;
    using MoviesRecommendationSystem.Services.Movies.Models;
    using MoviesRecommendationSystem.Services.Reviews;
    using MoviesRecommendationSystem.Services.Watchlists;

    using static WebConstants;
    using static Common.ControllerConstants.Movies;

    public class MoviesController : Controller
    {
        private readonly IMovieService movieService;
        private readonly IEditorService editorService;
        private readonly IWatchlistService watchlistService;
        private readonly IReviewService reviewService;
        private readonly IMapper mapper;

        public MoviesController(
            IMovieService moviesService,
            IEditorService editorsService,
            IWatchlistService watchlistService,
            IReviewService reviewService,
            IMapper mapper)
        {
            this.movieService = moviesService;
            this.editorService = editorsService;
            this.watchlistService = watchlistService;
            this.reviewService = reviewService;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.editorService.UserIsEditor(User.GetId()) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            var genres = this.movieService.AllGenres();

            this.PrepareViewBagGenres(genres);

            return View(new MovieFormModel());
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(MovieFormModel movie)
        {
            var editorId = this.editorService.IdByUser(User.GetId());

            if (editorId == 0 && !User.IsAdmin())
            {
                return BadRequest();
            }

            foreach (var genreId in movie.GenreIds)
                {
                    if (!this.movieService.GenreExists(int.Parse(genreId)))
                    {
                        ModelState.AddModelError(nameof(genreId), GenreDoesNotExistMessage);
                    }
                }

            if (!ModelState.IsValid)
            {
                var genres = this.movieService.AllGenres();

                this.PrepareViewBagGenres(genres);

                return View(movie);
            }

            var movieId = this.movieService.Create(
                movie.Title,
                (int)movie.ReleaseYear,
                (int)movie.Runtime,
                movie.Plot,
                movie.Language,
                movie.ImageUrl,
                movie.PlaybackUrl,
                movie.YoutubeTrailerId,
                movie.ImdbId,
                movie.DirectorName,
                movie.Studio,
                movie.StarringActors,
                movie.GenreIds,
                editorId,
                User.IsAdmin());

            TempData[GlobalMessageKey] = User.IsAdmin() ?
                MovieAddedPublicMessage
                : MovieAddedAwaitingApprovalMessage;

            return RedirectToAction(nameof(Details), new { id = movieId, info = movie.GetInfo() });
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = User.GetId();

            if (!this.editorService.UserIsEditor(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            var movieData = this.movieService.FormDetails(id);

            if (movieData.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var genres = this.movieService.AllGenres();
            var selectedGenreIds = this.movieService.SelectedGenreIds(id);

            this.PrepareViewBagGenres(genres, selectedGenreIds);

            var movieForm = this.mapper.Map<MovieFormModel>(movieData);

            movieForm.GenreIds = selectedGenreIds.ToList();

            return View(movieForm);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, MovieFormModel movie)
        {
            var editorId = this.editorService.IdByUser(User.GetId());

            if (editorId == 0 && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            foreach (var genreId in movie.GenreIds)
            {
                if (!this.movieService.GenreExists(int.Parse(genreId)))
                {
                    ModelState.AddModelError(nameof(genreId), GenreDoesNotExistMessage);
                }
            }

            if (!ModelState.IsValid)
            {
                var genres = this.movieService.AllGenres();

                this.PrepareViewBagGenres(genres);

                return View(movie);
            }

            if (!this.movieService.IsByEditor(id, editorId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.movieService.Edit(
                id,
                movie.Title,
                (int)movie.ReleaseYear,
                (int)movie.Runtime,
                movie.Plot,
                movie.Language,
                movie.ImageUrl,
                movie.PlaybackUrl,
                movie.YoutubeTrailerId,
                movie.ImdbId,
                movie.DirectorName,
                movie.Studio,
                movie.StarringActors,
                movie.GenreIds,
                User.IsAdmin());

            TempData[GlobalMessageKey] = User.IsAdmin() ?
                MovieEditedPublicMessage
                : MovieEditedAwaitingApprovalMessage;

            return RedirectToAction(nameof(Details), new { id, info = movie.GetInfo() });
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            var editorId = this.editorService.IdByUser(User.GetId());

            if (editorId == 0 && !User.IsAdmin())
            {
                return BadRequest();
            }

            if (!this.movieService.IsByEditor(id, editorId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.movieService.Delete(id);

            this.watchlistService.RemoveForAllUsers(id);

            return !User.IsAdmin() ?
                RedirectToAction(nameof(EditorContributions))
                : Redirect(AdminPanelRoute);
        }

        public IActionResult All([FromQuery] AllMoviesQueryModel query)
        {
            var queryResult = this.movieService.All(
                query.SelectedGenre,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllMoviesQueryModel.MoviesPerPage);

            query.Genres = this.movieService
                .AllGenres()
                .Select(g => g.Name);

            query.TotalMoviesCount = queryResult.TotalMovies;
            query.Movies = queryResult.Movies;

            return View(query);
        }

        [Authorize]
        public IActionResult EditorContributions()
        {
            if (!editorService.UserIsApprovedEditor(User.GetId()) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            var contributions = this.movieService
                .ByUser(User.GetId());

            return View(contributions);
        }

        public IActionResult Details(int id, string info)
        {
            var movie = this.movieService
                .Details(id);

            if (info != movie.GetInfo())
            {
                return BadRequest();
            }

            movie.Reviews = this.reviewService.ReviewsForMovie(id);

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.GetId();

                ViewBag.MovieIsInWatchlist = this.watchlistService.Exists(userId, id);
                ViewBag.WatchlistCount = this.watchlistService.Count(userId);
            }           

            return View(movie);
        }

        private void PrepareViewBagGenres(
            IEnumerable<MovieGenreServiceModel> genres,
            IEnumerable<string> selectedGenreIds = null)
        {
            var viewBagGenres = new List<SelectListItem>();

            foreach (var genre in genres)
            {
                viewBagGenres.Add(new SelectListItem
                {
                    Text = genre.Name,
                    Value = genre.Id.ToString()
                });
            }

            if (selectedGenreIds != null)
            {
                foreach (var genre in viewBagGenres)
                {
                    genre.Selected = selectedGenreIds.Contains(genre.Value);
                }
            }

            ViewBag.Genres = viewBagGenres;
        }
    }
}

MoviesRecommendationSystem/Controllers/WatchlistsController.cs
namespace MoviesRecommendationSystem.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MoviesRecommendationSystem.Infrastructure;
    using MoviesRecommendationSystem.Services.Movies;
    using MoviesRecommendationSystem.Services.Watchlists;

    using static Common.ControllerConstants.Watchlists;

    public class WatchlistsController : Controller
    {
        private readonly IWatchlistService watchlistService;
        private readonly IMovieService movieService;

        public WatchlistsController(IWatchlistService watchlistService, IMovieService movieService)
        {
            this.watchlistService = watchlistService;
            this.movieService = movieService;
        }

        [Authorize]
        [Route(AddRoute)]
        public IActionResult Add(int movieId)
        {
            var userId = User.GetId();

            var isSuccess = this.watchlistService.Add(userId, movieId);

            if (!isSuccess)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new 
            { 
                id = movieId,
                info = this.movieService.GetRouteInfo(movieId)
            });
        }

        [Authorize]
        [Route(RemoveRoute)]
        public IActionResult Remove(int movieId)
        {
            var userId = User.GetId();

            var isSuccess = this.watchlistService.Remove(userId, movieId);

            if (!isSuccess)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new
            {
                id = movieId,
                info = this.movieService.GetRouteInfo(movieId)
            });
        }

        [Authorize]
        public IActionResult All(string userId)
        {
            if (!User.Identity.IsAuthenticated || User.GetId() != userId)
            {
                return BadRequest();
            }

            var movies = this.watchlistService.GetMoviesDetailedByUser(userId);

            return View(movies);
        }
    }
}

MoviesRecommendationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@(ViewBag.Title ?? "MRS")</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=PT+Sans+Narrow&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Advent+Pro:wght@100&family=Inconsolata:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&family=Questrial&display=swap&family=Notable&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MRS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Add">Add Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="All">Collection</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav">
                        <li class="ml-2">
                            <partial name="_WatchlistPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (TempData.ContainsKey(WebConstants.GlobalMessageKey))
        {
            <div class="alert text-center" role="alert">
                @TempData[WebConstants.GlobalMessageKey]
            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer">
        <div class="footer-container">
            <div class="nav-left">
                <span>Movies-RS</span> @DateTime.UtcNow.Year
            </div>
            <div class="nav-right">
                <ul>
                    <li>
                        <a href="mailto:info@filmche.org" class="nav-link">Contact</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">
                            About
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MoviesRecommendationSystem/Views/Shared/_LayoutIndex.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@(ViewBag.Title ?? "MRS")</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/stars-animation.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=PT+Sans+Narrow&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Advent+Pro:wght@100&family=Inconsolata:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&family=Questrial&display=swap&family=Notable&display=swap" rel="stylesheet">"
</head>
<body>
    <header style="position: absolute; top:0; width:100%">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-transparent mb-3 position-relative">
            <div class="container">
                <a class="navbar-brand position-absolute" style="top: 8px" asp-area="" asp-controller="Home" asp-action="Index">MRS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Movies" asp-action="Add">Add Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Movies" asp-action="All">Collection</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartialDark" />
                    <ul class="navbar-nav">
                        <li class="ml-2">
                            <partial name="_WatchlistPartialDark" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (TempData.ContainsKey(WebConstants.GlobalMessageKey))
        {
            <div class="alert text-center text-light mt-5" role="alert">
                @TempData[WebConstants.GlobalMessageKey]
            </div>
        }

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <partial name="_CookieConsentPartial" />
    </div>

    <footer id="footer">
        <div class="footer-container">
            <div class="nav-left">
                <span>Movies-RS</span> @DateTime.UtcNow.Year
            </div>
            <div class="nav-right">
                <ul>
                    <li>
                        <a href="mailto:info@filmche.org" class="nav-link">Contact</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">
                            About
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MoviesRecommendationSystem/Views/Shared/_LoginPartialDark.cshtml
@using MoviesRecommendationSystem.Services.Editors

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject IEditorService Editors

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        var userIsEditor = Editors.UserIsEditor(User.GetId());
        var userIsApprovedEditor = Editors.UserIsApprovedEditor(User.GetId());
        var userIsAdmin = User.IsAdmin();

        if (!userIsAdmin)
        {
            if (userIsApprovedEditor)
            {
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Movies" asp-action="EditorContributions">Contributions</a>
                </li>
            }
            else if (!userIsEditor)
            {
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Editors" asp-action="Become">Become Editor</a>
                </li>
            }
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link text-light" asp-area="Admin" asp-controller="Movies" asp-action="All">Administration</a>
            </li>
        }

        <li class="nav-item">
            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Profile</a>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                <button type="submit" class="nav-link btn btn-link text-light" id="btn-logout">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
    }
</ul>

MoviesRecommendationSystem/Views/Shared/_LoginPartialLight.cshtml
@using MoviesRecommendationSystem.Services.Editors

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject IEditorService Editors

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        var userIsEditor = Editors.UserIsEditor(User.GetId());
        var userIsAdmin = User.IsAdmin();

        if (!userIsAdmin)
        {
            if (userIsEditor)
            {
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Movies" asp-action="EditorContributions">Contributions</a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Editors" asp-action="Become">Become Editor</a>
                </li>
            }
        }

        <li class="nav-item">
            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Profile</a>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                <button type="submit" class="nav-link btn btn-link text-light" id="btn-logout">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
    }
</ul>

MoviesRecommendationSystem/Views/Shared/_WatchlistPartial.cshtml
@using MoviesRecommendationSystem.Services.Watchlists.Models;

@inject SignInManager<User> SignInManager
@inject IWatchlistService WatchlistService

@{
    IEnumerable<WatchlistMovieServiceModel> watchlistMovies;
    int watchlistCount;
    bool userIsAuthenticated = User.Identity.IsAuthenticated;
    string userId;

    if (userIsAuthenticated)
    {
        userId = User.GetId();
        watchlistMovies = WatchlistService.GetMoviesByUser(userId);
        watchlistCount = watchlistMovies.Count();
    }
    else
    {
        userId = string.Empty;
        watchlistMovies = null;
        watchlistCount = 0;
    }
}

@if (userIsAuthenticated)
{
    <div class="dropdown show">
        <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img width="40px" height="40px" src="~/img/watchlist-logo.png" alt="Watchlist" />
            <span class="badge badge-dark" id="watchlist-counter">@watchlistCount</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">

            <div id="watchlist-dropdown">
                @foreach (var movie in watchlistMovies.Take(5))
                {
                    <a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id" asp-route-info="@movie.GetInfo()" id="movie-id-@movie.Id">
                        <span>@movie.Title</span>
                        <span class="watchlist-year">(@movie.ReleaseYear)</span>
                    </a>
                }
            </div>
            @if (!watchlistMovies.Any())
            {
                <span id="watchlist-empty" class="dropdown-item">(watchlist is empty)</span>
                <div id="watchlist-divider" class="dropdown-divider" style="display: none"></div>
                <a id="watchlist-see-all" class="dropdown-item" style="display: none" asp-area="" asp-controller="Watchlists" asp-action="All" asp-route-userId="@userId" id="watchlist-see-all">
                    See all
                </a>
            }
            else
            {
                <span id="watchlist-empty" class="dropdown-item" style="display: none">(watchlist is empty)</span>
                <div id="watchlist-divider" class="dropdown-divider"></div>
                <a id="watchlist-see-all" class="dropdown-item" asp-area="" asp-controller="Watchlists" asp-action="All" asp-route-userId="@userId" id="watchlist-see-all">
                    See all
                </a>
            }
        </div>
    </div>
}

MoviesRecommendationSystem/Views/Shared/_WatchlistPartialDark.cshtml
@using MoviesRecommendationSystem.Services.Watchlists.Models;

@inject SignInManager<User> SignInManager
@inject IWatchlistService WatchlistService

@{
    IEnumerable<WatchlistMovieServiceModel> watchlistMovies;
    int watchlistCount;
    bool userIsAuthenticated = User.Identity.IsAuthenticated;
    string userId;

    if (userIsAuthenticated)
    {
        userId = User.GetId();
        watchlistMovies = WatchlistService.GetMoviesByUser(userId);
        watchlistCount = watchlistMovies.Count();
    }
    else
    {
        userId = string.Empty;
        watchlistMovies = null;
        watchlistCount = 0;
    }
}

@if (userIsAuthenticated)
{
    <div class="dropdown show">
        <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img width="40px" height="40px" src="~/img/watchlist-logo-white.png" alt="Watchlist" />
            <span class="badge bg-white text-black" id="watchlist-counter">@watchlistCount</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="dropdownMenuLink">

            <div id="watchlist-dropdown">
                @foreach (var movie in watchlistMovies.Take(5))
                {
                    <a class="dropdown-item bg-dark text-white" asp-area="" asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id" asp-route-info="@movie.GetInfo()" id="@movie.Id">
                        <span>@movie.Title</span>
                        <span class="watchlist-year">(@movie.ReleaseYear)</span>
                    </a>
                }
            </div>
            @if (!watchlistMovies.Any())
            {
                <span id="watchlist-empty" class="dropdown-item bg-dark text-white">(watchlist is empty)</span>
                <div id="watchlist-divider" class="dropdown-divider" style="display: none"></div>
                <a id="watchlist-see-all" class="dropdown-item bg-dark text-white" style="display: none" asp-area="" asp-controller="Watchlists" asp-action="All" asp-route-userId="@userId" id="watchlist-see-all">
                    See all
                </a>
            }
            else
            {
                <span id="watchlist-empty" class="dropdown-item bg-dark text-white" style="display: none">(watchlist is empty)</span>
                <div id="watchlist-divider" class="dropdown-divider"></div>
                <a id="watchlist-see-all" class="dropdown-item bg-dark text-white" asp-area="" asp-controller="Watchlists" asp-action="All" asp-route-userId="@userId" id="watchlist-see-all">
                    See all
                </a>
            }
        </div>
    </div>
}