MoviesRecommendationSystem/Models/Api/Movies/AllMoviesApiRequestModel.cs
namespace MoviesRecommendationSystem.Models.Api.Movies
{
    using MoviesRecommendationSystem.Models.Enums;

    public class AllMoviesApiRequestModel
    {
        public int TotalMoviesCount { get; set; }

        public string SelectedGenre { get; init; }

        public string SearchTerm { get; init; }

        public MovieSorting Sorting { get; init; }

        public int MoviesPerPage { get; init; } = 10;

        public int CurrentPage { get; init; } = 1;
    }
}

MoviesRecommendationSystem/Models/Movies/AllMoviesQueryModel.cs
namespace MoviesRecommendationSystem.Models.Movies
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using MoviesRecommendationSystem.Models.Enums;
    using MoviesRecommendationSystem.Services.Movies.Models;

    public class AllMoviesQueryModel
    {
        public const int MoviesPerPage = 8;

        public int TotalMoviesCount { get; set; }

        public string SelectedGenre { get; init; }

        [Display(Name = "Search")]
        public string SearchTerm { get; init; }

        public MovieSorting Sorting { get; init; }

        public int CurrentPage { get; init; } = 1;

        public IEnumerable<string> Genres { get; set; }

        public IEnumerable<MovieServiceModel> Movies { get; set; }
    }
}

MoviesRecommendationSystem/Models/Movies/Enums/MovieSorting.cs
namespace MoviesRecommendationSystem.Models.Movies.Enums
{
    public enum MovieSorting
    {
        DateCreated = 0,
        DateCreatedDescending = 1,
        DateCreatedAscending = 2,
    }
}

MoviesRecommendationSystem/Models/Movies/MovieListingViewModel.cs
namespace MoviesRecommendationSystem.Models.Movies
{
    public class MovieListingViewModel
    {
        public int Id { get; init; }

        public string Title { get; init; }

        public int ReleaseYear { get; init; }

        public string Plot { get; init; }

        public string ImageUrl { get; init; }

        // IEnumerable<Genres> ...
    }
}

MoviesRecommendationSystem/Areas/Admin/Controllers/MoviesController.cs
namespace MoviesRecommendationSystem.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using MoviesRecommendationSystem.Services.Movies;

    public class MoviesController : AdminController
    {
        private readonly IMovieService movieService;

        public MoviesController(IMovieService movieService)
            => this.movieService = movieService;

        public IActionResult All() 
            => View(this.movieService.All(publicOnly: false).Movies);

        public IActionResult SwitchVisibility(int id)
        {
            this.movieService.SwitchVisibility(id);

            return RedirectToAction(nameof(All), new { publicOnly = false });
        }
    }
}

MoviesRecommendationSystem/Controllers/MoviesController.cs
namespace MoviesRecommendationSystem.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using AutoMapper;

    using MoviesRecommendationSystem.Infrastructure;
    using MoviesRecommendationSystem.Models.Movies;
    using MoviesRecommendationSystem.Services.Editors;
    using MoviesRecommendationSystem.Services.Movies;
    using MoviesRecommendationSystem.Services.Movies.Models;
    using MoviesRecommendationSystem.Services.Reviews;
    using MoviesRecommendationSystem.Services.Watchlists;

    using static WebConstants;
    using static Common.ControllerConstants.Movies;

    public class MoviesController : Controller
    {
        private readonly IMovieService movieService;
        private readonly IEditorService editorService;
        private readonly IWatchlistService watchlistService;
        private readonly IReviewService reviewService;
        private readonly IMapper mapper;

        public MoviesController(
            IMovieService moviesService,
            IEditorService editorsService,
            IWatchlistService watchlistService,
            IReviewService reviewService,
            IMapper mapper)
        {
            this.movieService = moviesService;
            this.editorService = editorsService;
            this.watchlistService = watchlistService;
            this.reviewService = reviewService;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.editorService.UserIsEditor(User.GetId()) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            var genres = this.movieService.AllGenres();

            this.PrepareViewBagGenres(genres);

            return View(new MovieFormModel());
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(MovieFormModel movie)
        {
            var editorId = this.editorService.IdByUser(User.GetId());

            if (editorId == 0 && !User.IsAdmin())
            {
                return BadRequest();
            }

            foreach (var genreId in movie.GenreIds)
                {
                    if (!this.movieService.GenreExists(int.Parse(genreId)))
                    {
                        ModelState.AddModelError(nameof(genreId), GenreDoesNotExistMessage);
                    }
                }

            if (!ModelState.IsValid)
            {
                var genres = this.movieService.AllGenres();

                this.PrepareViewBagGenres(genres);

                return View(movie);
            }

            var movieId = this.movieService.Create(
                movie.Title,
                (int)movie.ReleaseYear,
                (int)movie.Runtime,
                movie.Plot,
                movie.Language,
                movie.ImageUrl,
                movie.PlaybackUrl,
                movie.YoutubeTrailerId,
                movie.ImdbId,
                movie.DirectorName,
                movie.Studio,
                movie.StarringActors,
                movie.GenreIds,
                editorId,
                User.IsAdmin());

            TempData[GlobalMessageKey] = User.IsAdmin() ?
                MovieAddedPublicMessage
                : MovieAddedAwaitingApprovalMessage;

            return RedirectToAction(nameof(Details), new { id = movieId, info = movie.GetInfo() });
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = User.GetId();

            if (!this.editorService.UserIsEditor(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            var movieData = this.movieService.FormDetails(id);

            if (movieData.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var genres = this.movieService.AllGenres();
            var selectedGenreIds = this.movieService.SelectedGenreIds(id);

            this.PrepareViewBagGenres(genres, selectedGenreIds);

            var movieForm = this.mapper.Map<MovieFormModel>(movieData);

            movieForm.GenreIds = selectedGenreIds.ToList();

            return View(movieForm);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, MovieFormModel movie)
        {
            var editorId = this.editorService.IdByUser(User.GetId());

            if (editorId == 0 && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            foreach (var genreId in movie.GenreIds)
            {
                if (!this.movieService.GenreExists(int.Parse(genreId)))
                {
                    ModelState.AddModelError(nameof(genreId), GenreDoesNotExistMessage);
                }
            }

            if (!ModelState.IsValid)
            {
                var genres = this.movieService.AllGenres();

                this.PrepareViewBagGenres(genres);

                return View(movie);
            }

            if (!this.movieService.IsByEditor(id, editorId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.movieService.Edit(
                id,
                movie.Title,
                (int)movie.ReleaseYear,
                (int)movie.Runtime,
                movie.Plot,
                movie.Language,
                movie.ImageUrl,
                movie.PlaybackUrl,
                movie.YoutubeTrailerId,
                movie.ImdbId,
                movie.DirectorName,
                movie.Studio,
                movie.StarringActors,
                movie.GenreIds,
                User.IsAdmin());

            TempData[GlobalMessageKey] = User.IsAdmin() ?
                MovieEditedPublicMessage
                : MovieEditedAwaitingApprovalMessage;

            return RedirectToAction(nameof(Details), new { id, info = movie.GetInfo() });
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            var editorId = this.editorService.IdByUser(User.GetId());

            if (editorId == 0 && !User.IsAdmin())
            {
                return BadRequest();
            }

            if (!this.movieService.IsByEditor(id, editorId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.movieService.Delete(id);

            this.watchlistService.RemoveForAllUsers(id);

            return !User.IsAdmin() ?
                RedirectToAction(nameof(EditorContributions))
                : Redirect(AdminPanelRoute);
        }

        public IActionResult All([FromQuery] AllMoviesQueryModel query)
        {
            var queryResult = this.movieService.All(
                query.SelectedGenre,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllMoviesQueryModel.MoviesPerPage);

            query.Genres = this.movieService
                .AllGenres()
                .Select(g => g.Name);

            query.TotalMoviesCount = queryResult.TotalMovies;
            query.Movies = queryResult.Movies;

            return View(query);
        }

        [Authorize]
        public IActionResult EditorContributions()
        {
            if (!editorService.UserIsApprovedEditor(User.GetId()) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(EditorsController.Become), EditorsControllerName);
            }

            var contributions = this.movieService
                .ByUser(User.GetId());

            return View(contributions);
        }

        public IActionResult Details(int id, string info)
        {
            var movie = this.movieService
                .Details(id);

            if (info != movie.GetInfo())
            {
                return BadRequest();
            }

            movie.Reviews = this.reviewService.ReviewsForMovie(id);

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.GetId();

                ViewBag.MovieIsInWatchlist = this.watchlistService.Exists(userId, id);
                ViewBag.WatchlistCount = this.watchlistService.Count(userId);
            }           

            return View(movie);
        }

        private void PrepareViewBagGenres(
            IEnumerable<MovieGenreServiceModel> genres,
            IEnumerable<string> selectedGenreIds = null)
        {
            var viewBagGenres = new List<SelectListItem>();

            foreach (var genre in genres)
            {
                viewBagGenres.Add(new SelectListItem
                {
                    Text = genre.Name,
                    Value = genre.Id.ToString()
                });
            }

            if (selectedGenreIds != null)
            {
                foreach (var genre in viewBagGenres)
                {
                    genre.Selected = selectedGenreIds.Contains(genre.Value);
                }
            }

            ViewBag.Genres = viewBagGenres;
        }
    }
}

MoviesRecommendationSystem/Controllers/ReviewsController.cs
namespace MoviesRecommendationSystem.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MoviesRecommendationSystem.Infrastructure;
    using MoviesRecommendationSystem.Models.Reviews;
    using MoviesRecommendationSystem.Services.Movies;
    using MoviesRecommendationSystem.Services.Reviews;

    using static WebConstants;
    using static Common.ControllerConstants.Reviews;

    public class ReviewsController : Controller
    {
        private readonly IReviewService reviewService;
        private readonly IMovieService movieService;

        public ReviewsController(IReviewService reviewService, IMovieService movieService)
        {
            this.reviewService = reviewService;
            this.movieService = movieService;
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(AddReviewFormModel review)
        {
            if (!ModelState.IsValid)
            {
                TempData[GlobalMessageKey] = ReviewInvalidMessage;

                return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new
                {
                    id = review.MovieId,
                    info = this.movieService.GetRouteInfo(review.MovieId)
                });
            }

            var userId = User.GetId();

            if (this.reviewService.UserHasReview(review.MovieId, userId))
            {
                TempData[GlobalMessageKey] = UserHasReviewMessage;

                return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new
                {
                    id = review.MovieId,
                    info = this.movieService.GetRouteInfo(review.MovieId)
                });
            }

            this.reviewService.Create(
                userId,
                review.MovieId,
                review.Rating,
                review.Content);

            TempData[GlobalMessageKey] = AddSuccessfulMessage;

            return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new
            {
                id = review.MovieId,
                info = this.movieService.GetRouteInfo(review.MovieId)
            });
        }       

        [Authorize]
        public IActionResult Delete(int id, int movieId)
        {
            var reviewIsByUser = this.reviewService.BelongsToUser(id, User.GetId());

            if (!User.IsAdmin() && !reviewIsByUser)
            {
                return BadRequest();
            }

            this.reviewService.Delete(id);

            var info = this.movieService.GetRouteInfo(movieId);

            TempData[GlobalMessageKey] = DeleteSuccessfulMessage;

            return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new 
            { 
                id = movieId,
                info
            });
        }
    }
}

MoviesRecommendationSystem/Controllers/WatchlistsController.cs
namespace MoviesRecommendationSystem.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MoviesRecommendationSystem.Infrastructure;
    using MoviesRecommendationSystem.Services.Movies;
    using MoviesRecommendationSystem.Services.Watchlists;

    using static Common.ControllerConstants.Watchlists;

    public class WatchlistsController : Controller
    {
        private readonly IWatchlistService watchlistService;
        private readonly IMovieService movieService;

        public WatchlistsController(IWatchlistService watchlistService, IMovieService movieService)
        {
            this.watchlistService = watchlistService;
            this.movieService = movieService;
        }

        [Authorize]
        [Route(AddRoute)]
        public IActionResult Add(int movieId)
        {
            var userId = User.GetId();

            var isSuccess = this.watchlistService.Add(userId, movieId);

            if (!isSuccess)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new 
            { 
                id = movieId,
                info = this.movieService.GetRouteInfo(movieId)
            });
        }

        [Authorize]
        [Route(RemoveRoute)]
        public IActionResult Remove(int movieId)
        {
            var userId = User.GetId();

            var isSuccess = this.watchlistService.Remove(userId, movieId);

            if (!isSuccess)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(MoviesController.Details), MoviesControllerName, new
            {
                id = movieId,
                info = this.movieService.GetRouteInfo(movieId)
            });
        }

        [Authorize]
        public IActionResult All(string userId)
        {
            if (!User.Identity.IsAuthenticated || User.GetId() != userId)
            {
                return BadRequest();
            }

            var movies = this.watchlistService.GetMoviesDetailedByUser(userId);

            return View(movies);
        }
    }
}

MoviesRecommendationSystem/Views/Movies/All.cshtml
@model AllMoviesQueryModel

@{
    ViewBag.Title = "Collection - " + (Model.SelectedGenre ?? "All");
}

<form method="get">
    <div class="row" id="genre-selector">
        <ul class="collapse">
            <li class="li-genre-selector"><a class="genre-selector" href="/Movies/All">All</a></li>
            @foreach (var genre in Model.Genres)
            {
                <li class="li-genre-selector"><a class="genre-selector" href="?SelectedGenre=@genre">@genre</a></li>
            }
        </ul>
    </div>
</form>

@if (!Model.Movies.Any())
{
    <h2 id="movies-empty">Oops! We don't have any movie suggestions in the selected category.</h2>
}

<partial name="_MoviesPartial" model="@Model.Movies" />

@{
    var previousPage = Model.CurrentPage - 1;
    var nextPage = Model.CurrentPage + 1;

    if (previousPage < 1)
    {
        previousPage = 1;
    }

    bool hasNextPage = Model.CurrentPage * AllMoviesQueryModel.MoviesPerPage < Model.TotalMoviesCount;
}

<div class="row">
    <div class="pagination">
        @if (Model.CurrentPage > 1)
        {

            <a class="btn-pagination"
               asp-controller="Movies"
               asp-action="All"
               asp-route-currentPage="@previousPage"
               asp-route-selectedGenre="@Model.SelectedGenre"
               asp-route-sorting="@((int)Model.Sorting)"
               asp-route-searchTerm="@Model.SearchTerm">
                Previous
            </a>
        }
        @if (hasNextPage)
        {
            <a class="btn-pagination"
               asp-controller="Movies"
               asp-action="All"
               asp-route-currentPage="@nextPage"
               asp-route-selectedGenre="@Model.SelectedGenre"
               asp-route-sorting="@((int)Model.Sorting)"
               asp-route-searchTerm="@Model.SearchTerm">
                Next
            </a>
        }
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            var url = window.location.href;
            $("a").each(function () {
                if (url == (this.href)) {
                    $(this).closest("li").addClass("a-active");
                }
            });
        });
    </script>
}

MoviesRecommendationSystem/Views/Movies/Details.cshtml
@model MovieDetailsServiceModel

<div class="row movie-data">
    <div class="col-12 col-md-8 col-sm-10">
        <iframe type="text/html" width="100%" height="100%" src="https://www.youtube.com/embed/@(Model.YoutubeTrailerId)?controls=0&showinfo=0&modestbranding=1&playsinline=1&rel=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="col-md-4 col-sm-10">
        <p class="data-genres">
            @foreach (var genre in Model.Genres)
            {
                <span>@genre.ToUpper()</span>
            }
        </p>
        <p>
            <span id="movie-title">@Model.Title</span>
            <span id="release-year">, @Model.ReleaseYear</span>
        </p>
        <p class="data-plot">
            @Model.Plot
        </p>
        <span class="imdbRatingPlugin" data-title="@Model.ImdbId" data-style="p4">
            <a href="https://www.imdb.com/title/@(Model.ImdbId)/?ref_=plg_rt_1">
                <img width="37" height="17" src="https://www.nicepng.com/png/full/36-360403_8f068a-internet-movie-database.png" alt="@Model.Title (@Model.ReleaseYear) on IMDb" />
            </a>
        </span>
        <div class="watch-buttons">
            <form class="d-inline-block" action="@Model.PlaybackUrl">
                <input class="btn-watch" type="submit" value="Watch now" id="watch-now" />
            </form>
            @if (User.Identity.IsAuthenticated)
            {
                if (!ViewBag.MovieIsInWatchlist)
                {
                    <input class="btn-watch" type="button" value="Watch later" id="add-movie">
                    <input class="btn-watch" type="button" value="Remove from watchlist" id="remove-movie" style="display: none">
                }
                else
                {
                    <input class="btn-watch" type="button" value="Watch later" id="add-movie" style="display: none">
                    <input class="btn-watch" type="button" value="Remove from watchlist" id="remove-movie">
                }
            }
            else
            {
                <a class="btn-watch" id="btn-watch-later" asp-area="Identity" asp-page="/Account/Login">Watch later</a>
            }
            <div>

            </div>
            <div id="watchlist-notification" style="display: none;">
            </div>
        </div>
        <script>(function (d, s, id) { var js, stags = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) { return; } js = d.createElement(s); js.id = id; js.src = "https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/js/rating.js"; stags.parentNode.insertBefore(js, stags); })(document, "script", "imdb-rating-api");</script>
    </div>
</div>
<div id="rating-and-info">
    <div class="average-rating">
        @for (int i = 0; i < Model.AverageRating; i++)
        {
            <span class="star-active">★</span>
        }
        @for (int i = 0; i < 5 - Model.AverageRating; i++)
        {
            <span class="star-passive">☆</span>
        }
    </div>
    <div class="div-movie-info">
        <p class="movie-info">
            <span>@Model.Studio</span> presents a <span>@Model.ReleaseYear</span> film by <span>@Model.DirectorName</span><br />
            starring <span>@Model.StarringActors</span><br />
            runtime <span>@Model.Runtime min</span> language <span>@Model.Language</span>
        </p>
    </div>
</div>

<h2 id="reviews-title"><span>User reviews</span></h2>


<div class="reviews">
    @if (User.Identity.IsAuthenticated)
    {
        @if (Model.Reviews == null || !Model.Reviews.Any(r => r.UserId == User.GetId()))
        {
            <div class="div-add-review">
                <p>
                    <span class="d-block">Have you already watched this movie?</span>
                    <span class="d-block">Give us your thoughts!</span>
                </p>
                <input type="button" value="Add review" id="add-review">
            </div>
            <div class="new-review">
                <partial name="_ReviewFormPartial" model="@Model.ReviewFormModel" />
            </div>
        }

    }
    else
    {
        <div class="div-add-review">
            <p>
                Have you already watched this movie?
                Give us your thoughts!
            </p>
            <a class="btn-watch" asp-area="Identity" asp-page="/Account/Login" asp-route-returnUrl="@Url.Action("Details", "Movies", new { id = Model.Id, info = Model.GetInfo() })">Add review</a>
        </div>
    }
    @if (Model.Reviews != null)
    {
        <div>
            @foreach (var review in Model.Reviews)
            {       
                <hr />
                <div class="user-review">
                    <div class="user-data">
                        <p class="review-author">@review.Author</p>
                        <p class="review-publish-date">@review.DateCreated</p>
                        @if (User.Identity.IsAuthenticated && (User.IsAdmin() || review.UserId == User.GetId()))
                        {
                            <a class="btn-watch" asp-controller="Reviews" asp-action="Delete" asp-route-id="@review.Id" asp-route-movieId="@Model.Id">Delete</a>
                        }
                    </div>
                    <div class="review-data">
                        <p class="review-rating">
                            @for (int i = 0; i < review.Rating; i++)
                            {
                                <span class="star-active-small">★</span>
                            }
                            @for (int i = 0; i < 5 - review.Rating; i++)
                            {
                                <span class="star-passive-small">☆</span>
                            }
                        </p>
                        <p class="review-content">@review.Content</p>                   
                    </div>
                </div>
            }
        </div>
    }
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
        $(document).ready(function () {
            $('#add-movie').click(function () {
                $.ajax({
                    url: '@Url.Action("Add", "Watchlists", new { movieId = Model.Id })',
                    complete: function () {
                        $('#add-movie').fadeOut(200, function () {
                            $('#remove-movie').fadeIn(100);
                        });

                        $('#watchlist-counter').html(parseInt($('#watchlist-counter').html(), 10) + 1);

                        $('#watchlist-dropdown').prepend('<a class="dropdown-item" href="@Model.Title-@Model.ReleaseYear" id="movie-id-@Model.Id"><span>@Model.Title</span><span class="watchlist-year"> (@Model.ReleaseYear)</span></a>');

                        if ($('#watchlist-counter').text() == "1") {
                            $('#watchlist-empty').hide();
                            $('#watchlist-divider').show();
                            $('#watchlist-see-all').show();
                        }

                        if ($('#watchlist-dropdown').children().length > 5) {
                            $('#watchlist-dropdown').children().last().remove();
                        }

                        $('#watchlist-notification')
                            .css('color', 'darkgreen')
                            .text('✓ Successfully added @Model.Title (@Model.ReleaseYear) to your watchlist!')
                            .fadeIn(300);
                    }
                })
            });

            $('#remove-movie').click(function () {
                $.ajax({
                    url: '@Url.Action("Remove", "Watchlists", new { movieId = Model.Id })',
                    complete: function () {
                        $('#remove-movie').fadeOut(200, function () {
                            $('#add-movie').fadeIn(100);
                        });

                        $('#watchlist-counter').html(parseInt($('#watchlist-counter').html(), 10) - 1);

                        if ($('#watchlist-counter').text() == "0") {
                            $('#watchlist-see-all').hide();
                            $('#watchlist-divider').hide();
                            $('#watchlist-empty').show();
                        }

                        $('#watchlist-dropdown > #movie-id-@Model.Id').remove();

                        $('#watchlist-notification')
                            .css('color', 'darkred')
                            .text('✓ Successfully removed @Model.Title (@Model.ReleaseYear) from your watchlist!')
                            .fadeIn(300);
                    }
                })
            })
        });

        $('#add-review').click(function () {
            $('.review-form').show(300);
            $('#add-review').hide();
        })
    </script>
}

MoviesRecommendationSystem/Views/Movies/EditorContributions.cshtml
@model IEnumerable<MovieServiceModel>

@{
    ViewBag.Title = "My Contributions";
    ViewBag.AllowEdit = true;
}

@if (!Model.Any())
{
    <div class="contributions">
        <h2 id="contributions-empty-title">Hey, you still haven't added any movies!</h2>
        <a class="btn-general d-inline-block" asp-controller="Movies" asp-action="Add">Add movie</a>
    </div>
}
else
{
    <h2 id="contributions-title">Movies added by you</h2>
    <partial name="_MoviesPartial" model="@Model" />
}

MoviesRecommendationSystem/Views/Movies/_MoviesPartial.cshtml
@model IEnumerable<MovieServiceModel>

<div class="row">
    @foreach (var movie in Model)
    {
        <div class="card">
            <a href="Details/@movie.Id">
                <img class="card-img-top" src="@movie.ImageUrl" alt="@movie.Title (@movie.ReleaseYear)">
            </a>
            <div class="card-body">
                <p class="genres">
                    @foreach (var genre in movie.Genres)
                    {
                        <span>@genre.ToUpper()</span>
                    }
                </p>
                <a href="Details/@movie.Id">
                    <h5 class="card-title">@movie.Title, @movie.ReleaseYear</h5>
                </a>
                <p class="card-text">@movie.Plot</p>
                @if (ViewBag.AllowEdit == true || User.IsAdmin())
                {
                    <div class="row" id="movie-buttons">
                        <a asp-controller="Movies" asp-action="Edit" asp-route-id="@movie.Id" class="btn btn-outline-dark">Edit</a>
                        <a asp-controller="Movies" asp-action="Delete" asp-route-id="@movie.Id" class="btn btn-danger">Delete</a>
                    </div>
                }
            </div>
        </div>
    }
</div>

MoviesRecommendationSystem/Views/Movies/_ReviewFormPartial.cshtml
@model AddReviewFormModel

<form method="post" asp-controller="Reviews" asp-action="Add">
    <div class="review-form">
        @*<h3>
            <span>
                Your review
            </span>
        </h3>*@
        <div class="position-relative">
            <div class="form-group star-rating col-1 ml-2">
                @for (int i = 5; i >= 1; i--)
                {
                    <input asp-for="Rating" type="radio" name="rating" value="@(i)" id="star-@i"><label class="star-radio" asp-for="Rating" for="star-@i">☆</label>
                }
                <span asp-validation-for="Rating" class="small text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <textarea asp-for="Content" class="form-control" rows="3"></textarea>
            <span asp-validation-for="Content" class="small text-danger"></span>
        </div>
        <div hidden class="form-group hidden">
            <input asp-for="MovieId" value="@Model.MovieId" />
        </div>
        <button type="submit" class="btn-watch">Submit</button>
    </div>
</form>
    